
import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.MouseInfo;
import java.awt.Point;
import java.awt.PointerInfo;
import java.awt.geom.Path2D;
import static java.lang.Math.cos;
import static java.lang.Math.pow;
import static java.lang.Math.sin;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ULAŞ
 */
public class paint extends javax.swing.JFrame {

    /**
     * Creates new form paint
     */
    public paint() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        menuBar1 = new java.awt.MenuBar();
        menu1 = new java.awt.Menu();
        menu2 = new java.awt.Menu();
        menuBar2 = new java.awt.MenuBar();
        menu3 = new java.awt.Menu();
        menu4 = new java.awt.Menu();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jPopupMenu3 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem22 = new javax.swing.JMenuItem();
        jButton1 = new javax.swing.JButton();
        silgi = new javax.swing.JButton();
        temizle = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        kalınlıkarttırma = new javax.swing.JButton();
        kalınlıkazaltma = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        kalemrengimenu = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        arkaplanrengimenu = new javax.swing.JMenu();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenuItem19 = new javax.swing.JMenuItem();
        jMenuItem20 = new javax.swing.JMenuItem();
        jMenuItem21 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem23 = new javax.swing.JMenuItem();
        jMenuItem24 = new javax.swing.JMenuItem();
        jMenuItem25 = new javax.swing.JMenuItem();
        jMenuItem26 = new javax.swing.JMenuItem();

        menu1.setLabel("File");
        menuBar1.add(menu1);

        menu2.setLabel("Edit");
        menuBar1.add(menu2);

        menu3.setLabel("File");
        menuBar2.add(menu3);

        menu4.setLabel("Edit");
        menuBar2.add(menu4);

        jMenuItem1.setText("jMenuItem1");

        jMenu4.setText("File");
        jMenuBar2.add(jMenu4);

        jMenu5.setText("Edit");
        jMenuBar2.add(jMenu5);

        jMenuItem22.setText("jMenuItem22");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Paint");

        jButton1.setText("jButton1");

        silgi.setText("Silgi");
        silgi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                silgiActionPerformed(evt);
            }
        });

        temizle.setText("Temizle");
        temizle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                temizleActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 693, Short.MAX_VALUE)
        );

        kalınlıkarttırma.setText("+");
        kalınlıkarttırma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kalınlıkarttırmaActionPerformed(evt);
            }
        });

        kalınlıkazaltma.setText("-");
        kalınlıkazaltma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kalınlıkazaltmaActionPerformed(evt);
            }
        });

        jLabel1.setText("Kalınlık:");

        jTextField1.setText("4");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton2.setText("Kalem");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        kalemrengimenu.setText("Kalem Rengi");

        jMenuItem2.setText("Siyah");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        kalemrengimenu.add(jMenuItem2);

        jMenuItem3.setText("Beyaz");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        kalemrengimenu.add(jMenuItem3);

        jMenuItem4.setText("Kırmızı");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        kalemrengimenu.add(jMenuItem4);

        jMenuItem5.setText("Yeşil");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        kalemrengimenu.add(jMenuItem5);

        jMenuItem6.setText("Mavi");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        kalemrengimenu.add(jMenuItem6);

        jMenuItem7.setText("Sarı");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        kalemrengimenu.add(jMenuItem7);

        jMenuItem8.setText("Gri");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        kalemrengimenu.add(jMenuItem8);

        jMenuItem9.setText("Koyu yeşil");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        kalemrengimenu.add(jMenuItem9);

        jMenuItem10.setText("Mor");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        kalemrengimenu.add(jMenuItem10);

        jMenuItem11.setText("Kahverengi");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        kalemrengimenu.add(jMenuItem11);

        jMenuBar1.add(kalemrengimenu);

        arkaplanrengimenu.setText("Arkaplan Rengi");

        jMenuItem12.setText("Siyah");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        arkaplanrengimenu.add(jMenuItem12);

        jMenuItem13.setText("Beyaz");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        arkaplanrengimenu.add(jMenuItem13);

        jMenuItem14.setText("Kırmızı");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        arkaplanrengimenu.add(jMenuItem14);

        jMenuItem15.setText("Yeşil");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        arkaplanrengimenu.add(jMenuItem15);

        jMenuItem16.setText("Mavi");
        jMenuItem16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem16ActionPerformed(evt);
            }
        });
        arkaplanrengimenu.add(jMenuItem16);

        jMenuItem17.setText("Sarı");
        jMenuItem17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem17ActionPerformed(evt);
            }
        });
        arkaplanrengimenu.add(jMenuItem17);

        jMenuItem18.setText("Gri");
        jMenuItem18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem18ActionPerformed(evt);
            }
        });
        arkaplanrengimenu.add(jMenuItem18);

        jMenuItem19.setText("Koyu Yeşil");
        jMenuItem19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem19ActionPerformed(evt);
            }
        });
        arkaplanrengimenu.add(jMenuItem19);

        jMenuItem20.setText("Mor");
        jMenuItem20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem20ActionPerformed(evt);
            }
        });
        arkaplanrengimenu.add(jMenuItem20);

        jMenuItem21.setText("Kahverengi");
        jMenuItem21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem21ActionPerformed(evt);
            }
        });
        arkaplanrengimenu.add(jMenuItem21);

        jMenuBar1.add(arkaplanrengimenu);

        jMenu1.setText("Şekiller");

        jMenuItem23.setText("Kare");
        jMenuItem23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem23ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem23);

        jMenuItem24.setText("Üçgen");
        jMenuItem24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem24ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem24);

        jMenuItem25.setText("Daire");
        jMenuItem25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem25ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem25);

        jMenuItem26.setText("Yıldız");
        jMenuItem26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem26ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem26);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(silgi, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(temizle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(kalınlıkarttırma)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kalınlıkazaltma)
                .addContainerGap(1370, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(silgi)
                    .addComponent(temizle)
                    .addComponent(kalınlıkarttırma)
                    .addComponent(kalınlıkazaltma)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>
int cizimsecmi=1;
int sekil=0;static int a=4;
int renk1;
int renk2;
int renk3;
int renk4=255;
int renk5=255;
int renk6=255;
    void kalem(int nokta1,int nokta2){
     Graphics g = jPanel1.getGraphics();
        Graphics2D g2d = (Graphics2D) g;
            g2d.setStroke(new BasicStroke(a));
        Color buttonrenk = new Color(renk1,renk2,renk3);
        g2d.setColor(buttonrenk);
        g2d.drawLine(nokta1,nokta2,nokta1,nokta2);
}
    void silgi(int nokta1,int nokta2){
        Graphics g = jPanel1.getGraphics();
        Graphics2D g2d = (Graphics2D) g;
            g2d.setStroke(new BasicStroke(a));
        Color buttonrenk = new Color(renk4,renk5,renk6);
        g2d.setColor(buttonrenk);
        g2d.drawLine(nokta1,nokta2,nokta1,nokta2);
    }
    void kare(int nokta1,int nokta2){
        Graphics g = jPanel1.getGraphics();
        Graphics2D g2d = (Graphics2D) g;
            g2d.setStroke(new BasicStroke(a));
            Color buttonrenk = new Color(renk1,renk2,renk3);
            g2d.setColor(buttonrenk);
            PointerInfo a = MouseInfo.getPointerInfo();
        Point b = a.getLocation();
        int x = (int) b.getX();
        int y = (int) b.getY();
            g2d.drawLine(nokta1-60,nokta2-60,nokta1+60,nokta2-60);
            g2d.drawLine(nokta1-60, nokta2-60, nokta1-60, nokta2+60);
            g2d.drawLine(nokta1-60,nokta2+60,nokta1+60,nokta2+60);
            g2d.drawLine(nokta1+60,nokta2-60,nokta1+60,nokta2+60);

    }
    void ucgen(int nokta1,int nokta2){
        Graphics g = jPanel1.getGraphics();
        Graphics2D g2d = (Graphics2D) g;
            g2d.setStroke(new BasicStroke(a));
            Color buttonrenk = new Color(renk1,renk2,renk3);
            g2d.setColor(buttonrenk);
        g2d.drawLine(nokta1,nokta2-60,nokta1-60,nokta2+60);
        g2d.drawLine(nokta1,nokta2-60,nokta1+60,nokta2+60);
        g2d.drawLine(nokta1-60,nokta2+60,nokta1+60,nokta2+60);
    }
    void daire(int nokta1,int nokta2){
        Graphics g = jPanel1.getGraphics();
        Graphics2D g2d = (Graphics2D) g;
            g2d.setStroke(new BasicStroke(a));
            Color buttonrenk = new Color(renk1,renk2,renk3);
            g2d.setColor(buttonrenk);
        g2d.drawOval(nokta1-60,nokta2-60,120,120);
    }
    void yildiz(int x,int y){
        Graphics g = jPanel1.getGraphics();
        Graphics2D g2d = (Graphics2D) g;
            g2d.setStroke(new BasicStroke(a));
            Color buttonrenk = new Color(renk1,renk2,renk3);
            g2d.setColor(buttonrenk);
            //1
            g2d.drawLine(x,y-20,x+10,y);
            //2
            g2d.drawLine(x+10,y,x+30,y);
            //3
            g2d.drawLine(x+30,y,x+10,y+10);
            //4
            g2d.drawLine(x+10,y+10,x+20,y+30);
            //5
            g2d.drawLine(x+20,y+30,x,y+20);
            //6
            g2d.drawLine(x,y+20,x-20,y+30);
            //7
            g2d.drawLine(x-20,y+30,x-10,y+10);
            //8
            g2d.drawLine(x-10,y+10,x-30,y);
            //9
            g2d.drawLine(x-30,y,x-10,y);
            //10
            g2d.drawLine(x-10,y,x,y-20);

    }
    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {
       if(cizimsecmi==1){
           kalem(evt.getX(),evt.getY());
       }
       else if(cizimsecmi == 2){
           silgi(evt.getX(),evt.getY());
       }

    }

    private void temizleActionPerformed(java.awt.event.ActionEvent evt) {
        repaint();
        cizimsecmi=1;
    }

    private void kalınlıkarttırmaActionPerformed(java.awt.event.ActionEvent evt) {
       a++;
       String b = Integer.toString(a);
       jTextField1.setText(b);
    }

    private void kalınlıkazaltmaActionPerformed(java.awt.event.ActionEvent evt) {
        a--;
        String b = Integer.toString(a);
        jTextField1.setText(b);
    }

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {
          if(cizimsecmi==1){
           kalem(evt.getX(),evt.getY());
       }
       else if(cizimsecmi == 2){
           silgi(evt.getX(),evt.getY());
       }
         else if(cizimsecmi==3){
           kare(evt.getX(),evt.getY());
       }
         else if(cizimsecmi == 4){
             ucgen(evt.getX(),evt.getY());
         }
          else if(cizimsecmi == 5){
             daire(evt.getX(),evt.getY());
         }

          else if(cizimsecmi == 7){
              yildiz(evt.getX(),evt.getY());
          }
    }

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {
        renk1=0;
        renk2=255;
        renk3=0;

    }

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {
        renk1=0;
        renk2=0;
        renk3=0;

    }

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {
        renk1=255;
        renk2=255;
        renk3=255;

    }

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {
        renk1=255;
        renk2=0;
        renk3=0;

    }

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {
        renk1=0;
        renk2=0;
        renk3=255;

    }

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {
        renk1=255;
        renk2=255;
        renk3=0;

    }

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {
        renk1=128;
        renk2=128;
        renk3=128;

    }

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {
        renk1=0;
        renk2=128;
        renk3=0;

    }

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {
        renk1=128;
        renk2=0;
        renk3=128;

    }

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {
        renk1 = 210;
        renk2 = 105;
        renk3 =30;

    }

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {
        renk4=0;
        renk5=0;
        renk6=0;
        Color arkaplanrenk = new Color(renk4,renk5,renk6);
                jPanel1.setBackground(arkaplanrenk);
    }

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {
        renk4=255;
        renk5=255;
        renk6=255;
        Color arkaplanrenk = new Color(renk4,renk5,renk6);
                jPanel1.setBackground(arkaplanrenk);
    }

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {
       renk4=255;
        renk5=0;
        renk6=0;
        Color arkaplanrenk = new Color(renk4,renk5,renk6);
                jPanel1.setBackground(arkaplanrenk);
    }

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {
        renk4=0;
        renk5=255;
        renk6=0;
        Color arkaplanrenk = new Color(renk4,renk5,renk6);
                jPanel1.setBackground(arkaplanrenk);
    }

    private void jMenuItem16ActionPerformed(java.awt.event.ActionEvent evt) {
        renk4=0;
        renk5=0;
        renk6=255;
        Color arkaplanrenk = new Color(renk4,renk5,renk6);
                jPanel1.setBackground(arkaplanrenk);
    }

    private void jMenuItem17ActionPerformed(java.awt.event.ActionEvent evt) {
        renk4=255;
        renk5=255;
        renk6=0;
        Color arkaplanrenk = new Color(renk4,renk5,renk6);
                jPanel1.setBackground(arkaplanrenk);
    }

    private void jMenuItem18ActionPerformed(java.awt.event.ActionEvent evt) {
        renk4=128;
        renk5=128;
        renk6=128;
        Color arkaplanrenk = new Color(renk4,renk5,renk6);
                jPanel1.setBackground(arkaplanrenk);
    }

    private void jMenuItem19ActionPerformed(java.awt.event.ActionEvent evt) {
        renk4=0;
        renk5=128;
        renk6=0;
        Color arkaplanrenk = new Color(renk4,renk5,renk6);
                jPanel1.setBackground(arkaplanrenk);
    }

    private void jMenuItem20ActionPerformed(java.awt.event.ActionEvent evt) {
        renk4=128;
        renk5=0;
        renk6=128;
        Color arkaplanrenk = new Color(renk4,renk5,renk6);
                jPanel1.setBackground(arkaplanrenk);
    }

    private void jMenuItem21ActionPerformed(java.awt.event.ActionEvent evt) {
       renk4=210;
        renk5=105;
        renk6=30;
        Color arkaplanrenk = new Color(renk4,renk5,renk6);
                jPanel1.setBackground(arkaplanrenk);
    }

    private void silgiActionPerformed(java.awt.event.ActionEvent evt) {

        cizimsecmi=2;
    }

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {
       String b = Integer.toString(a);
                jTextField1.setText(b);
    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
        cizimsecmi=1;
    }

    private void jMenuItem23ActionPerformed(java.awt.event.ActionEvent evt) {
        cizimsecmi = 3;
    }

    private void jMenuItem24ActionPerformed(java.awt.event.ActionEvent evt) {
        cizimsecmi = 4;
    }

    private void jMenuItem25ActionPerformed(java.awt.event.ActionEvent evt) {
        cizimsecmi = 5;
    }

    private void jMenuItem26ActionPerformed(java.awt.event.ActionEvent evt) {
        cizimsecmi = 7;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(paint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(paint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(paint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(paint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new paint().setVisible(true);

            }
        });
    }


    // Variables declaration - do not modify
    private javax.swing.JMenu arkaplanrengimenu;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem21;
    private javax.swing.JMenuItem jMenuItem22;
    private javax.swing.JMenuItem jMenuItem23;
    private javax.swing.JMenuItem jMenuItem24;
    private javax.swing.JMenuItem jMenuItem25;
    private javax.swing.JMenuItem jMenuItem26;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JPopupMenu jPopupMenu3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JMenu kalemrengimenu;
    private javax.swing.JButton kalınlıkarttırma;
    private javax.swing.JButton kalınlıkazaltma;
    private java.awt.Menu menu1;
    private java.awt.Menu menu2;
    private java.awt.Menu menu3;
    private java.awt.Menu menu4;
    private java.awt.MenuBar menuBar1;
    private java.awt.MenuBar menuBar2;
    private javax.swing.JButton silgi;
    private javax.swing.JButton temizle;
    // End of variables declaration

    private Color setColor(int i, int i0, int i1) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
